// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-XgU9boFaZXl9WA_TqqXDZqu9FRu-u0',
    appId: '1:1035807106026:android:4a87df7f561312635ac893',
    messagingSenderId: '1035807106026',
    projectId: 'pokedexds-mobile-i-trabalho-01',
    storageBucket: 'pokedexds-mobile-i-trabalho-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2UVXFHNhbUnJOinHuv_XSf3Pg7JjQVPY',
    appId: '1:1035807106026:ios:2de0c3c02716221e5ac893',
    messagingSenderId: '1035807106026',
    projectId: 'pokedexds-mobile-i-trabalho-01',
    storageBucket: 'pokedexds-mobile-i-trabalho-01.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCTQSjOZ-yX-00rtOZRnUZQMN64SZK2vjE",
    authDomain: "pokedexds-mobile-i-trabalho-01.firebaseapp.com",
    projectId: "pokedexds-mobile-i-trabalho-01",
    storageBucket: "pokedexds-mobile-i-trabalho-01.firebasestorage.app",
    messagingSenderId: "1035807106026",
    appId: "1:1035807106026:web:712065aabfd5d2c75ac893",
  );

}